//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string MainCategory { get; set; }
        public string SubCategory { get; set; }
        public string Image { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EditedBy { get; set; }
        public System.DateTime EditedOn { get; set; }
    }
}
